import {
  SiAmazonec2,
  SiFlask,
  SiMysql,
  SiNextdotjs,
  SiPostgresql,
  SiSupabase,
  SiTypescript,
  SiVite,
  SiReacthookform,
  SiStyledcomponents,
  SiShadcnui,
  SiRedux,
  SiExpress,
  SiAmazons3,
  SiGraphql, 
  SiApollographql, 
} from "react-icons/si";
import { RiTailwindCssFill, RiJavascriptFill } from "react-icons/ri";
import { FaAws, FaReact, FaPython, FaGithub, FaCss3Alt, FaHtml5,  } from "react-icons/fa";
import { TbBrandOauth } from "react-icons/tb";
import { BiWorld } from "react-icons/bi";

export const technologiesNodes = {
  nextjs: <SiNextdotjs />,
  tailwind: <RiTailwindCssFill />,
  supabase: <SiSupabase />,
  react: <FaReact />,
  oauth: <TbBrandOauth />,
  chadcn: <SiShadcnui />,
  redux: <SiRedux />,
  typescript: <SiTypescript />,
  styled: <SiStyledcomponents />,
  aws: <FaAws />,
  vite: <SiVite />,
  mysql: <SiMysql />,
  postgres: <SiPostgresql />,
  express: <SiExpress />,
  s3: <SiAmazons3 />,
  world: <BiWorld />,
  github: <FaGithub />,
  python: <FaPython />,
  flask: <SiFlask />,
  ecs: <SiAmazonec2 />,
  reactForm: <SiReacthookform />,
  css: <FaCss3Alt />,
  html: <FaHtml5 />,
  javascript: <RiJavascriptFill />,
  graphql: <SiGraphql />,
  apollographql: <SiApollographql />,
};